name: Flutter Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      
      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2 

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk  

      - name: Generate and Push Git Tag
        run: |
          # Generate a unique tag based on the current date and time
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          NEW_TAG="v1.0.${TIMESTAMP}"
          
          # Configure Git user
          git config user.name "GitHub Actions"
          git config user.email "malukishtiaq@gmail.com"
          
          # Create and push the new tag
          git tag -a $NEW_TAG -m "Release version $NEW_TAG"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} $NEW_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use PROD Environment Secret
        run: echo "${{ secrets.PROD_SECRET }}"
        env:
          DEV_SECRET: ${{ secrets.PROD_SECRET }}